"""Pydantic schemas for the Template Tool."""

from pydantic import BaseModel, Field

from schemas import register_schema # Import the decorator


@register_schema("TemplateToolInput") # Register with class name
class TemplateToolInput(BaseModel):
    """Input schema for the Template Tool."""

    parameter: str = Field(..., description="The input string parameter for the tool")
    result: str = Field(..., description="The result generated by the template tool.")
    error: str | None = Field(None, description="Error message if execution failed.")


@register_schema("TemplateToolOutput") # Register with class name
class TemplateToolOutput(BaseModel):
    """Output schema for the Template Tool."""

    result: str = Field(..., description="The processed result string")
