# Name of this GitHub Actions workflow.
name: Security Scan (Semgrep)

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: [ "main" ] # Or your main branch name
  # Schedule the CI job (this method uses cron syntax):
  schedule:
    - cron: '35 10 * * 1' # Example: Scan every Monday at 10:35 UTC

permissions:
  contents: read # needed to read code
  # Add other permissions as needed by Semgrep rules

jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: Semgrep Scan
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: ubuntu-latest

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - name: Checkout code
        uses: actions/checkout@v4

      # Run the "semgrep scan" command on the command line of the docker image.
      - name: Run Semgrep Scan
        run: semgrep scan --config auto
        # Removed the previous 'uses: semgrep/semgrep-action@v2' step 